
services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    restart: always
    ports:
      - "3307:3306"  # Expose port 3307 on your host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql      # persistent data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # optional: auto-init script
